# example workflow for Black Duck SCA scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: Black Duck Fix PR
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck_sca:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck SCA Scan
      uses: blackduck-inc/black-duck-security-scan@v2.1.1
      env:
        DETECT_PROJECT_NAME: MJ-Temporary
      with:
        blackducksca_url: ${{ vars.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackducksca_fixpr_enabled: true
        blackducksca_prComment_enabled: true
        blackducksca_reports_sarif_create: true
        blackducksca_upload_sarif_report: true
        blackducksca_policy_badges_create: true
        
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true
